# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Recipe1.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTableView,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.SaveRecipe = QPushButton(self.centralwidget)
        self.SaveRecipe.setObjectName(u"SaveRecipe")
        self.SaveRecipe.setGeometry(QRect(320, 410, 181, 32))
        self.NewRecipeButton = QPushButton(self.centralwidget)
        self.NewRecipeButton.setObjectName(u"NewRecipeButton")
        self.NewRecipeButton.setGeometry(QRect(10, 280, 100, 41))
        font = QFont()
        font.setFamilies([u"Calibri"])
        font.setPointSize(16)
        font.setBold(True)
        self.NewRecipeButton.setFont(font)
        self.RecipeListCombo = QComboBox(self.centralwidget)
        self.RecipeListCombo.setObjectName(u"RecipeListCombo")
        self.RecipeListCombo.setGeometry(QRect(530, 410, 171, 32))
        self.RecipeListCombo.setEditable(True)
        self.RecipeListCombo.setMaxVisibleItems(20)
        self.CalLab = QLabel(self.centralwidget)
        self.CalLab.setObjectName(u"CalLab")
        self.CalLab.setGeometry(QRect(30, 60, 131, 31))
        font1 = QFont()
        font1.setPointSize(15)
        font1.setBold(True)
        self.CalLab.setFont(font1)
        self.cal_line = QLineEdit(self.centralwidget)
        self.cal_line.setObjectName(u"cal_line")
        self.cal_line.setGeometry(QRect(180, 60, 113, 31))
        self.cal_line.setFont(font1)
        self.cal_line.setStyleSheet(u"background-color: rgba(156, 255, 92, 153);")
        self.cal_line.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.Protlab = QLabel(self.centralwidget)
        self.Protlab.setObjectName(u"Protlab")
        self.Protlab.setGeometry(QRect(30, 110, 121, 31))
        self.Protlab.setFont(font1)
        self.prot_line = QLineEdit(self.centralwidget)
        self.prot_line.setObjectName(u"prot_line")
        self.prot_line.setGeometry(QRect(180, 110, 113, 31))
        font2 = QFont()
        font2.setBold(True)
        self.prot_line.setFont(font2)
        self.prot_line.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.CancelButton = QPushButton(self.centralwidget)
        self.CancelButton.setObjectName(u"CancelButton")
        self.CancelButton.setGeometry(QRect(390, 470, 231, 61))
        font3 = QFont()
        font3.setPointSize(18)
        font3.setBold(True)
        font3.setItalic(True)
        self.CancelButton.setFont(font3)
        self.CancelButton.setAutoFillBackground(False)
        self.CancelButton.setStyleSheet(u"background-color: rgb(255, 79, 69);")
        self.IngredientsLabel = QLabel(self.centralwidget)
        self.IngredientsLabel.setObjectName(u"IngredientsLabel")
        self.IngredientsLabel.setGeometry(QRect(407, 19, 211, 31))
        font4 = QFont()
        font4.setPointSize(23)
        self.IngredientsLabel.setFont(font4)
        self.IngredientsLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.RecipeTableView = QTableView(self.centralwidget)
        self.RecipeTableView.setObjectName(u"RecipeTableView")
        self.RecipeTableView.setGeometry(QRect(320, 60, 391, 341))
        self.RecipeTableView.setEditTriggers(QAbstractItemView.EditTrigger.AllEditTriggers)
        self.AddRowButton = QPushButton(self.centralwidget)
        self.AddRowButton.setObjectName(u"AddRowButton")
        self.AddRowButton.setGeometry(QRect(320, 440, 371, 32))
        palette = QPalette()
        brush = QBrush(QColor(240, 57, 49, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        self.AddRowButton.setPalette(palette)
        font5 = QFont()
        font5.setPointSize(21)
        font5.setBold(False)
        self.AddRowButton.setFont(font5)
        self.NewRecipeName = QLineEdit(self.centralwidget)
        self.NewRecipeName.setObjectName(u"NewRecipeName")
        self.NewRecipeName.setGeometry(QRect(10, 320, 301, 21))
        font6 = QFont()
        font6.setFamilies([u"Calibri"])
        font6.setPointSize(15)
        self.NewRecipeName.setFont(font6)
        self.FatLab = QLabel(self.centralwidget)
        self.FatLab.setObjectName(u"FatLab")
        self.FatLab.setGeometry(QRect(30, 160, 131, 31))
        self.FatLab.setFont(font1)
        self.fat_line = QLineEdit(self.centralwidget)
        self.fat_line.setObjectName(u"fat_line")
        self.fat_line.setGeometry(QRect(180, 160, 113, 31))
        self.fat_line.setFont(font1)
        self.fat_line.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.CarbLab = QLabel(self.centralwidget)
        self.CarbLab.setObjectName(u"CarbLab")
        self.CarbLab.setGeometry(QRect(30, 210, 121, 21))
        self.CarbLab.setFont(font1)
        self.carb_line = QLineEdit(self.centralwidget)
        self.carb_line.setObjectName(u"carb_line")
        self.carb_line.setGeometry(QRect(180, 210, 113, 31))
        self.carb_line.setFont(font1)
        self.carb_line.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.CloseButton = QPushButton(self.centralwidget)
        self.CloseButton.setObjectName(u"CloseButton")
        self.CloseButton.setGeometry(QRect(10, 400, 191, 121))
        palette1 = QPalette()
        brush1 = QBrush(QColor(243, 243, 243, 217))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        brush2 = QBrush(QColor(48, 68, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.CloseButton.setPalette(palette1)
        font7 = QFont()
        font7.setPointSize(20)
        font7.setBold(True)
        font7.setItalic(True)
        self.CloseButton.setFont(font7)
        self.CloseButton.setStyleSheet(u"background-color: rgb(48, 68, 255);")
        self.titlab = QLabel(self.centralwidget)
        self.titlab.setObjectName(u"titlab")
        self.titlab.setGeometry(QRect(37, 10, 251, 20))
        self.version_line = QLineEdit(self.centralwidget)
        self.version_line.setObjectName(u"version_line")
        self.version_line.setGeometry(QRect(290, 0, 61, 41))
        font8 = QFont()
        font8.setPointSize(20)
        font8.setBold(True)
        self.version_line.setFont(font8)
        self.version_line.setAlignment(Qt.AlignmentFlag.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 37))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(tooltip)
        self.SaveRecipe.setToolTip(QCoreApplication.translate("MainWindow", u"Don't forget to hit return", None))
#endif // QT_CONFIG(tooltip)
        self.SaveRecipe.setText(QCoreApplication.translate("MainWindow", u"Save Recipes", None))
        self.NewRecipeButton.setText(QCoreApplication.translate("MainWindow", u"New Recipe", None))
        self.CalLab.setText(QCoreApplication.translate("MainWindow", u"Calories per gram", None))
        self.Protlab.setText(QCoreApplication.translate("MainWindow", u"Protein per gram", None))
#if QT_CONFIG(whatsthis)
        self.CancelButton.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Cancel the current recipe</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.CancelButton.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.IngredientsLabel.setText(QCoreApplication.translate("MainWindow", u"Ingredients", None))
#if QT_CONFIG(tooltip)
        self.AddRowButton.setToolTip(QCoreApplication.translate("MainWindow", u"Add row to table", None))
#endif // QT_CONFIG(tooltip)
        self.AddRowButton.setText(QCoreApplication.translate("MainWindow", u"AddRow", None))
#if QT_CONFIG(tooltip)
        self.NewRecipeName.setToolTip(QCoreApplication.translate("MainWindow", u"Name of new recipe", None))
#endif // QT_CONFIG(tooltip)
        self.FatLab.setText(QCoreApplication.translate("MainWindow", u"Fat per gram", None))
        self.CarbLab.setText(QCoreApplication.translate("MainWindow", u"Carbs per gram", None))
        self.CloseButton.setText(QCoreApplication.translate("MainWindow", u"Close Window", None))
        self.titlab.setText(QCoreApplication.translate("MainWindow", u"Calory Program by Andi Klein -- version", None))
    # retranslateUi

